name: Keep Backend Alive (Days 16â€“31)

on:
  schedule:
    - cron: "*/15 0 16-31 * *"
    - cron: "*/10 5-23 16-31 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -sSf https://puka-comfort-backend.onrender.com/api/news/posts/ || true
